# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_review_app', '0003_auto_20170721_0339'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reviewed',
            field=models.ManyToManyField(related_name='reviewed', to='belt_review_app.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='book',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='belt_review_app.Book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='belt_review_app.User'),
            preserve_default=False,
        ),
    ]
