# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_authors', '0002_auto_20170719_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
