# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-26 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
